"""empty message

Revision ID: 957726e496c5
Revises:
Create Date: 2023-07-22 15:45:55.690469

"""
from alembic import op
import sqlalchemy as sa
from app.models import recipient


# revision identifiers, used by Alembic.
revision = '957726e496c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    seed()


def seed():
    recipients = recipient.Recipient.seed()
    op.bulk_insert(recipient.Recipient.__table__,
        recipients,
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipient')
    # ### end Alembic commands ###
